import type { VisionAnalysisResult, WeeklyDataPoint, DocumentTypeCount, Template } from './types'

export const MOCK_ANALYSES: VisionAnalysisResult[] = [
  {
    id: 'dnv_mock_001',
    documentType: 'invoice',
    documentTypeLabel: 'Factura / Invoice',
    confidence: 96,
    extractedText: 'FACTURA FACT-48291\nFecha: 15/05/2026\nTotal: $24,500.00 MXN',
    fields: {
      invoice_number: 'FACT-48291',
      date: '15/05/2026',
      supplier: 'TechSolutions México S.A.',
      customer: 'Empresa Global Corp',
      total: '$24,500.00 MXN',
      currency: 'MXN',
    },
    extractedFields: [
      { key: 'invoice_number', value: 'FACT-48291', confidence: 99 },
      { key: 'total', value: '$24,500.00 MXN', confidence: 97 },
      { key: 'date', value: '15/05/2026', confidence: 98 },
    ],
    summary: 'Valid invoice from TechSolutions México for professional services totaling $24,500.00 MXN.',
    warnings: [],
    suggestedActions: ['Save to ERP system', 'Notify accounting team', 'Create payment reminder'],
    processingTime: 2340,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    fileName: 'factura_techsolutions_mayo.pdf',
    fileSize: 245678,
    fileType: 'application/pdf',
    rawJson: '{}',
    tags: ['Factura / Invoice', 'high-confidence', 'auto-classified'],
  },
  {
    id: 'dnv_mock_002',
    documentType: 'payment_receipt',
    documentTypeLabel: 'Comprobante de Pago',
    confidence: 94,
    extractedText: 'COMPROBANTE SPEI\nTRX-928391\nMonto: $8,750.00 MXN',
    fields: {
      transaction_id: 'TRX-928391',
      amount: '$8,750.00 MXN',
      sender: 'María Hernández Ruiz',
      receiver: 'DeepNode Industries S.A.',
      status: 'COMPLETADO ✓',
      date: '18/05/2026',
    },
    extractedFields: [
      { key: 'transaction_id', value: 'TRX-928391', confidence: 95 },
      { key: 'amount', value: '$8,750.00 MXN', confidence: 96 },
    ],
    summary: 'Bank transfer confirmation. Amount: $8,750.00 MXN. Status: Completed.',
    warnings: [],
    suggestedActions: ['Save to CRM', 'Notify finance team', 'Create invoice record'],
    processingTime: 1890,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    fileName: 'comprobante_spei_mayo.jpg',
    fileSize: 387432,
    fileType: 'image/jpeg',
    rawJson: '{}',
    tags: ['Comprobante de Pago', 'high-confidence', 'auto-classified'],
  },
  {
    id: 'dnv_mock_003',
    documentType: 'vehicle_plate',
    documentTypeLabel: 'Placa Vehicular',
    confidence: 88,
    extractedText: 'PLACA: ABC-123-D\nTipo: Sedan\nRegión: CDMX',
    fields: {
      plate_number: 'ABC-123-D',
      vehicle_type: 'Sedan',
      region: 'CDMX',
      color: 'Blanco',
    },
    extractedFields: [
      { key: 'plate_number', value: 'ABC-123-D', confidence: 91 },
      { key: 'region', value: 'CDMX', confidence: 85 },
    ],
    summary: 'Vehicle plate ABC-123-D detected. Sedan registered in CDMX.',
    warnings: [{ code: 'IMAGE_QUALITY', message: 'Image resolution could be improved.', severity: 'low' }],
    suggestedActions: ['Search in vehicle database', 'Log access timestamp'],
    processingTime: 1240,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    fileName: 'placa_vehiculo_entrada.jpg',
    fileSize: 512890,
    fileType: 'image/jpeg',
    rawJson: '{}',
    tags: ['Placa Vehicular', 'review-needed', 'auto-classified'],
  },
  {
    id: 'dnv_mock_004',
    documentType: 'contract',
    documentTypeLabel: 'Contrato',
    confidence: 91,
    extractedText: 'CONTRATO CTR-2024-0089\nVigencia: 12 meses\nValor: $150,000.00 MXN',
    fields: {
      contract_number: 'CTR-2024-0089',
      party_a: 'DeepNode Industries S.A.',
      party_b: 'Empresa Global Corp',
      value: '$150,000.00 MXN',
      effective_date: '01/01/2026',
      expiration_date: '31/12/2026',
    },
    extractedFields: [
      { key: 'contract_number', value: 'CTR-2024-0089', confidence: 94 },
      { key: 'value', value: '$150,000.00 MXN', confidence: 89 },
    ],
    summary: 'Annual services contract between DeepNode Industries and Empresa Global Corp. Value: $150,000.00 MXN.',
    warnings: [],
    suggestedActions: ['Schedule review reminder', 'Set expiration alert', 'Send to legal team'],
    processingTime: 2890,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    fileName: 'contrato_servicios_2026.pdf',
    fileSize: 892345,
    fileType: 'application/pdf',
    rawJson: '{}',
    tags: ['Contrato', 'high-confidence', 'auto-classified'],
  },
]

export const MOCK_WEEKLY_DATA: WeeklyDataPoint[] = [
  { day: 'Lun', documents: 12, confidence: 91 },
  { day: 'Mar', documents: 18, confidence: 88 },
  { day: 'Mié', documents: 24, confidence: 94 },
  { day: 'Jue', documents: 15, confidence: 92 },
  { day: 'Vie', documents: 31, confidence: 96 },
  { day: 'Sáb', documents: 8, confidence: 89 },
  { day: 'Dom', documents: 5, confidence: 85 },
]

export const MOCK_DOCUMENT_TYPES: DocumentTypeCount[] = [
  { type: 'Facturas', count: 42, color: '#06b6d4' },
  { type: 'Comprobantes', count: 28, color: '#10b981' },
  { type: 'Tickets', count: 19, color: '#8b5cf6' },
  { type: 'Contratos', count: 11, color: '#ef4444' },
  { type: 'Placas', count: 8, color: '#f59e0b' },
  { type: 'Otros', count: 5, color: '#64748b' },
]

export const TEMPLATES: Template[] = [
  {
    id: 'tpl_invoice',
    name: 'Invoice Extractor',
    description: 'Extract invoice number, amounts, RFC, tax data, and payment terms from invoices and facturas.',
    documentType: 'invoice',
    icon: 'FileText',
    fields: ['invoice_number', 'date', 'supplier', 'customer', 'subtotal', 'tax', 'total', 'currency', 'payment_method'],
    color: '#06b6d4',
    category: 'Finance',
  },
  {
    id: 'tpl_receipt',
    name: 'Payment Receipt Validator',
    description: 'Validate and extract bank transfer details, SPEI transactions, and payment confirmations.',
    documentType: 'payment_receipt',
    icon: 'CreditCard',
    fields: ['bank', 'transaction_id', 'amount', 'sender', 'receiver', 'date', 'status'],
    color: '#10b981',
    category: 'Finance',
  },
  {
    id: 'tpl_plate',
    name: 'Vehicle Plate Reader',
    description: 'Identify and extract vehicle license plate numbers from photos with regional detection.',
    documentType: 'vehicle_plate',
    icon: 'Car',
    fields: ['plate_number', 'vehicle_type', 'region', 'color'],
    color: '#f59e0b',
    category: 'Security',
  },
  {
    id: 'tpl_id',
    name: 'ID Document Scanner',
    description: 'Extract personal data from INE, passport, CURP, and other official identification documents.',
    documentType: 'id_document',
    icon: 'IdCard',
    fields: ['document_type', 'full_name', 'birth_date', 'id_number', 'expiration'],
    color: '#ec4899',
    category: 'KYC',
  },
  {
    id: 'tpl_contract',
    name: 'Contract Summary',
    description: 'Analyze legal contracts to extract parties, dates, obligations, risks, and key terms.',
    documentType: 'contract',
    icon: 'ScrollText',
    fields: ['contract_number', 'party_a', 'party_b', 'effective_date', 'expiration_date', 'value'],
    color: '#ef4444',
    category: 'Legal',
  },
  {
    id: 'tpl_ticket',
    name: 'Ticket OCR',
    description: 'Extract merchant, items, totals, and payment methods from point-of-sale receipts.',
    documentType: 'receipt',
    icon: 'Receipt',
    fields: ['merchant', 'date', 'items_count', 'total', 'payment_method'],
    color: '#8b5cf6',
    category: 'Finance',
  },
  {
    id: 'tpl_cfdi',
    name: 'CFDI Document Reader',
    description: 'Validate and extract data from Mexican CFDI 4.0 fiscal documents with SAT verification.',
    documentType: 'cfdi',
    icon: 'FileBadge',
    fields: ['uuid', 'version', 'issuer_rfc', 'receiver_rfc', 'total', 'voucher_type'],
    color: '#14b8a6',
    category: 'Fiscal',
  },
  {
    id: 'tpl_product',
    name: 'Product Image Analyzer',
    description: 'Analyze product images to detect labels, barcodes, text, and product information.',
    documentType: 'product_image',
    icon: 'Package',
    fields: ['document_class', 'text_detected', 'barcodes', 'qr_codes'],
    color: '#3b82f6',
    category: 'Commerce',
  },
]
